name: Unzip Project

on:
  push:
    branches: [ "main" ]

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Unzip project
        run: |
          sudo apt-get update && sudo apt-get install -y unzip
          unzip -o adars-foods-full.zip -d ./unzipped
          rsync -a ./unzipped/ ./   # move extracted files to repo root
          rm -rf ./unzipped
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Unzipped project automatically" || echo "No changes to commit"
          git push
